import assert from 'node:assert/strict';
import { createServer } from 'vite';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import RAPIER from '@dimforge/rapier3d-compat';
import * as THREE from 'three';
const server=await createServer({optimizeDeps:{noDiscovery:true,include:[]},cacheDir:join(tmpdir(),'shamal-extreme-check'),server:{middlewareMode:true,hmr:false,ws:false},appType:'custom'});
try {
  const {ExtremeRules}=await server.ssrLoadModule('/src/engine/ExtremeRules.ts');
  const {ExtremeCollisions}=await server.ssrLoadModule('/src/engine/ExtremeCollisions.ts');
  const {ActorImpacts}=await server.ssrLoadModule('/src/world/ActorImpacts.ts');
  const rules=new ExtremeRules();
  rules.damage(100,0);assert.equal(rules.health,100);assert.equal(rules.destroyed,false);
  assert(rules.setEnabled(true,0));rules.damage(100,1000);assert.equal(rules.health,100,'spawn grace');
  rules.impact(.17,1300);assert.equal(rules.health,100,'gravity/resting contact causes no damage');
  rules.damage(40,1300);assert.equal(rules.health,60);
  rules.damage(40,1400);assert.equal(rules.health,60,'one collision is not charged every physics step');
  assert(rules.damage(100,1700));assert.equal(rules.health,0);assert.equal(rules.respawnAt,6700);
  assert.equal(rules.setEnabled(false,2000),false,'cannot bypass destruction timer');
  assert.equal(rules.damage(100,3000),false);assert.equal(rules.respawnAt,6700,'cannot extend the timer with another hit');
  assert.equal(rules.tick(6699),false);assert.equal(rules.tick(6700),true);assert.equal(rules.health,100);assert.equal(rules.tick(7000),false);
  rules.damage(100,7000);assert.equal(rules.health,100,'respawn grace');
  rules.setEnabled(false,9000);rules.damage(100,10000);assert.equal(rules.health,100);
  await RAPIER.init();
  const world=new RAPIER.World({x:0,y:0,z:0});world.integrationParameters.dt=1/60;
  const physics=new ExtremeCollisions(world);
  const body=world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(0,0,-6).setCanSleep(false));
  body.setAdditionalMass(1000,true);body.enableCcd(true);
  const player=world.createCollider(RAPIER.ColliderDesc.cuboid(.5,.5,.9).setDensity(0).setActiveEvents(RAPIER.ActiveEvents.CONTACT_FORCE_EVENTS),body);
  const actor={id:0,kind:'vehicle',active:true,down:false,x:0,y:0,z:0,yaw:0,halfX:1,halfY:1,halfZ:1};
  body.setLinvel({x:0,y:0,z:20},true);
  let deltaV=0,hits=0;
  for(let i=0;i<35;i++) {
    physics.sync([{name:'traffic',actors:[actor]}],body.translation());world.step(physics.events);
    deltaV=Math.max(deltaV,physics.drain(player,1000,1/60,()=>{hits++;actor.down=true;}));
  }
  assert(deltaV>5,'real Rapier contact impulse must be reported');assert.equal(hits,1,'one hit per actor');assert(body.translation().z<0,'traffic blocks the vehicle');
  physics.clear();assert.equal(world.bodies.len(),1,'removes all kinematic proxies');
  body.setTranslation({x:0,y:0,z:-6},true);body.setLinvel({x:0,y:0,z:20},true);
  for(let i=0;i<35;i++)world.step();assert(body.translation().z>2,'normal mode passes through roaming actors');
  const impacts=new ActorImpacts('camel',[.48,1.3,1.65],1.3,.45),dummy=new THREE.Object3D();
  dummy.position.set(10,0,20);impacts.pose(0,dummy,0,()=>0);assert(impacts.hit(0));assert(!impacts.hit(0));
  dummy.position.set(100,0,100);impacts.pose(0,dummy,1,()=>0);
  assert.equal(impacts.actors[0].active,false);assert(Math.abs(dummy.position.z-20)<2,'fallen model stays at impact location');
  assert(Math.abs(dummy.quaternion.z)>.6,'animal falls onto its side');
  const bird=new ActorImpacts('bird',[.85,.2,.36],0);
  dummy.position.set(0,8,0);dummy.quaternion.identity();bird.pose(0,dummy,0,()=>0);bird.hit(0);
  bird.pose(0,dummy,.1,()=>0);assert(dummy.position.y>7,'hit birds fall rather than snap to the ground');
  bird.pose(0,dummy,2,()=>0);assert(dummy.position.y>=0&&dummy.position.y<.1,'bird settles above ground');
  const {ExtremeEffects}=await server.ssrLoadModule('/src/world/ExtremeEffects.ts');
  const fx=new ExtremeEffects((x,z)=>x*.2+z*.1);
  for(let i=0;i<20;i++)fx.blood(i,0);
  const stains=fx.group.children[0].geometry;
  assert(stains.drawRange.count<=stains.attributes.position.count,'blood pool stays bounded');
  assert(stains.attributes.position.array.every(Number.isFinite),'terrain-conforming blood geometry is finite');
  fx.explode({x:0,y:3,z:0});fx.update(.2);
  assert(fx.group.children[1].instanceMatrix.array.every(Number.isFinite),'explosion matrices are finite');
  fx.clear();assert.equal(stains.drawRange.count,0);assert.equal(fx.group.children[1].count,0);
  impacts.reset();assert.equal(impacts.actors.length,0);physics.events.free();world.free();
  console.log('PASS: opt-in isolation, damage thresholds, cooldown, exact five-second respawn, grace periods, real traffic collisions, single actor hit, normal-mode pass-through, fallen pose and cleanup.');
} finally {await server.close();}
